name: Lint Code, Check Format, Run Tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check:
    runs-on: windows-latest
    steps:
      # Checkout your Git repo
      - uses: actions/checkout@v2
      # Install aftman and all aftman tools (rojo and mantle)
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Generate Sourcemap
      - name: Install Wally Modules
        run: scripts/wally-install.cmd
      # Lint Types
      - name: Lint unit tests
        run: luau-lsp analyze --sourcemap sourcemap.json --base-luaurc .luaurc --defs testez.d.luau tests
      - name: Lint story books
        run: luau-lsp analyze --sourcemap sourcemap.json --base-luaurc .luaurc stories
      - name: Lint source code
        run: luau-lsp analyze --sourcemap sourcemap.json --base-luaurc .luaurc src
      # Check Code Format
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0 # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: --config-path stylua.toml --check src
