name: Check

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check-format:
    runs-on: windows-latest
    steps:
      - name: Checkout your Git repo
        uses: actions/checkout@v2

      - name: Check Format [Source code]
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --config-path stylua.toml --check src

      - name: Check Format [Story books]
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --config-path stylua.toml --check stories

      - name: Check Format [Unit tests]
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --config-path stylua.toml --check tests

  build-dev-game:
    runs-on: Windows-Latest
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Build dev game
        run: scripts/dev-build.cmd

      - name: Upload dev game build
        uses: alehechka/upload-tartifact@v2
        with:
          name: dev-game-build
          path: out/rojo/game.rbxl

  lint-code:
    runs-on: windows-latest
    needs: build-dev-game
    steps:
      - name: Checkout your Git repo
        uses: actions/checkout@v2

      - name: Install aftman and all aftman tools (rojo and mantle)
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Download game build
        uses: alehechka/download-tartifact@v2
        with:
          name: dev-game-build

      - name: Install Wally Modules
        run: scripts/wally-install.cmd dev.project.json

      - name: Download Roblox Definitions File
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/refs/heads/main/scripts/globalTypes.d.luau" -OutFile "globalTypes.d.luau"

      - name: Lint unit tests
        run: luau-lsp analyze --sourcemap sourcemap.json --base-luaurc .luaurc --ignore **/ServerPackages/** --ignore **/DevPackages/** --ignore **/Packages/** --ignore **/node_modules/** --defs globalTypes.d.luau --defs globals/testez.d.luau tests
      - name: Lint story books
        run: luau-lsp analyze --sourcemap sourcemap.json --base-luaurc .luaurc --ignore **/ServerPackages/** --ignore **/DevPackages/** --ignore **/Packages/** --ignore **/node_modules/** --defs globalTypes.d.luau stories
      - name: Lint source code
        run: luau-lsp analyze --sourcemap sourcemap.json --base-luaurc .luaurc --ignore **/ServerPackages/** --ignore **/DevPackages/** --ignore **/Packages/** --ignore **/node_modules/** --defs globalTypes.d.luau src

  unit-tests:
    runs-on: windows-latest
    needs: build-dev-game
    steps:
      - name: Checkout your Git repo
        uses: actions/checkout@v2

      - name: Download game build
        uses: alehechka/download-tartifact@v2
        with:
          name: dev-game-build

      - name: Run Tests
        run: python3 scripts/python/upload_and_run_tasks.py out/rojo/game.rbxl tests/run.luau -o out/tests.txt
        env:
          ROBLOX_API_KEY: ${{ secrets.TEST_RUNNER_OPEN_CLOUD_API_KEY }}
          ROBLOX_UNIVERSE_ID: ${{ vars.TEST_RUNNER_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ vars.TEST_RUNNER_PLACE_ID }}
