name: Release
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: Windows-Latest
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: scripts/rojo-build.cmd

      - name: Tar place build
        run: tar -cvf out/rojo/game.tar out/rojo/game.rbxl

      - name: Upload place build
        uses: actions/upload-artifact@v4
        with:
          name: place-build
          path: out/rojo/game.rbxl

  deploy:
    runs-on: Windows-Latest
    needs: build
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Download builded place
        uses: actions/download-artifact@v4
        with:
          name: place-build
          path: out/rojo/game.tar

      - name: Extract place build
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          cwd: ./out/rojo
          files: game.tar

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy project
        run: mantle deploy
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}

  release-github-version:
    runs-on: Windows-Latest
    needs: build
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Download builded place
        uses: actions/download-artifact@v4
        with:
          name: place-build
          path: out/rojo/game.tar

      - name: Extract place build
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          cwd: ./out/rojo
          files: game.tar

      - name: Setup node v20.8.1
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1

      - name: Install node modules
        run: npm i

      - name: Install node CI modules
        run: npm ci

      - name: Release GitHub
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
