name: Release
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: Windows-Latest
    steps:
      # Checkout your Git repo
      - name: Checkout git files
        uses: actions/checkout@v2
      # Install aftman and all aftman tools (rojo and mantle)
      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Build the project with rojo
      - name: Build project
        run: scripts/rojo-build.cmd
      # Deploy the project with mantle
      - name: Deploy project
        run: mantle deploy
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}

  release-github-version:
    runs-on: Windows-Latest
    needs: build-and-deploy
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      # Checkout your Git repo
      - name: Checkout git files
        uses: actions/checkout@v2
      # Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: 20.8.1
      - run: npm i
      - run: npm ci
      # Release Git Hub
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
